global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'citadel'
    static_configs:
      - targets: ['localhost:9100']
    metrics_path: /metrics

  - job_name: 'coredns'
    static_configs:
      - targets: ['localhost:9153']
    metrics_path: /metrics
